- name: Check WinRM reachability from AAP
  hosts: all
  gather_facts: false
  
  vars:
      domain_name: "sdxmecm.test"


  tasks:

    - name: Check DNS resolution from VM
      ansible.windows.win_powershell:
        script: |
          nslookup {{ domain_name }}
      register: dns_check

    - name: Check Kerberos connectivity (port 88)
      ansible.windows.win_powershell:
        script: |
          Test-NetConnection {{ domain_name }} -Port 88
      register: kerberos_check

    - name: Check LDAP connectivity (port 389)
      ansible.windows.win_powershell:
        script: |
          Test-NetConnection {{ domain_name }} -Port 389
      register: ldap_check
      

    - name: Check time sync
      ansible.windows.win_powershell:
        script: |
          w32tm /query /status
      register: time_check
      

    - name: Check domain controller discovery
      ansible.windows.win_powershell:
        script: |
          nltest /dsgetdc:{{ domain_name }}
      register: dc_check
      

    - name: Check if already domain joined
      ansible.windows.win_powershell:
        script: |
          (Get-WmiObject Win32_ComputerSystem).Domain
      register: domain_status
      

    - name: Show pre-check summary
      ansible.builtin.debug:
        msg:
          DNS: "{{ dns_check.output | default('FAILED') }}"
          Kerberos: "{{ kerberos_check.output | default('FAILED') }}"
          LDAP: "{{ ldap_check.output | default('FAILED') }}"
          Time: "{{ time_check.output | default('FAILED') }}"
          DC: "{{ dc_check.output | default('FAILED') }}"
          Domain: "{{ domain_status.output | default('FAILED') }}"
