---
- name: Verify connectivity to SCCM server
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    sccm_server_ip: 172.17.74.101
    ansible_connection: local
    ansible_shell_type: sh
    ansible_shell_executable: /bin/sh

  tasks:
    - name: Check WinRM HTTPS port (5986) from controller
      ansible.builtin.wait_for:
        host: 172.17.74.101
        port: 5986
        timeout: 10
        state: started


